# Generated by Django 3.2.9 on 2024-10-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='otpNumber',
            field=models.TextField(blank=True, default=0, max_length=6),
        ),
    ]
