# Generated by Django 3.2.9 on 2025-07-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_otpnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='appointmentDate',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='appointmentTime',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
