# Generated by Django 3.2.9 on 2024-10-10 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models
import multiselectfield.db.fields
import product.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('categoryParentId', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(blank=True, max_length=15, null=True)),
                ('validUpto', models.DateTimeField(blank=True, null=True)),
                ('valueInPercent', models.FloatField(default=0.0)),
                ('currentRedemptions', models.IntegerField(blank=True, default=0, null=True)),
                ('maxDiscount', models.FloatField(blank=True, null=True)),
                ('maxRedemptions', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tagCloud', multiselectfield.db.fields.MultiSelectField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Office and desk Plants', 'Office and desk Plants'), ('Terrace Plants', 'Terrace Plants'), ('Balcony Plants', 'Balcony Plants'), ('Living Room Plants', 'Living Room Plants'), ('Bedroom Plants', 'Bedroom Plants'), ('Bathroom Plants', 'Bathroom Plants'), ('Kitchen Plants', 'Kitchen Plants'), ('Ac Room Plants', 'Table Top Plants'), ('Air purifying Plants', 'Air purifying Plants'), ('Winter Plant', 'Winter Plant'), ('Summer Plant', 'Summer Plant'), ('Monsoon Plant', 'Monsoon Plant'), ('All Season Plant', 'All Season Plant'), ('All Season Flower Plant', 'All Season Flower Plant')], default='', max_length=249)),
                ('sluggedName', models.SlugField(default='', editable=False, max_length=500)),
                ('productName', models.CharField(max_length=100)),
                ('productTable', django_bleach.models.BleachField()),
                ('productDescription', django_bleach.models.BleachField()),
                ('productMRP', models.FloatField()),
                ('productSalePrice', models.FloatField()),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('ExtraLarge', 'Extra Large'), ('NotApplicable', 'Not Applicable')], max_length=100, null=True)),
                ('season', models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Monsoon', 'Monsoon'), ('AllSeasons', 'All Seasons')], max_length=100, null=True)),
                ('occasion', models.CharField(blank=True, choices=[('NewYear', 'NewYear'), ('Holi', 'Holi'), ('WorldPlantDay', 'World Plant Day'), ('Rakhi', 'Rakhi'), ('OtherOccasions', 'Other Occasions')], max_length=100, null=True)),
                ('giftPack', models.CharField(blank=True, choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Corporate', 'Corporate'), ('Other', 'Other'), ('NotApplicable', 'Not Applicable')], max_length=100, null=True)),
                ('comboPack', models.CharField(blank=True, choices=[('Buy1Get1 Free', 'Buy 1 Get 1 Free'), ('Buy2Get1Free', 'Buy 2 Get 1 Free'), ('Other', 'Other'), ('NotApplicable', 'Not Applicable')], max_length=100, null=True)),
                ('saleCounter', models.IntegerField(default=0)),
                ('is_live', models.BooleanField(default=False)),
                ('taxPercent', models.FloatField()),
                ('totalUnitsSold', models.IntegerField(blank=True, default=0, null=True)),
                ('unitsInStock', models.IntegerField(blank=True, default=0, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRatingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('mediafile', models.FileField(blank=True, upload_to=product.models.ProductRatingMedia.path_and_rename)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Ratings Media',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('reviewSubject', models.CharField(default='', max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('reviewDescription', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(50)])),
                ('is_live', models.BooleanField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('productmedia', models.FileField(blank=True, upload_to=product.models.ProductMedia.path_and_rename)),
                ('mainimage', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Media',
            },
        ),
    ]
