# Generated by Django 3.2.9 on 2025-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='appointmenttime',
            field=models.CharField(blank=True, choices=[('09:00 AM - 12:00 PM', '09:00AM-12:00PM'), ('12:00 PM - 03:00 PM', '12:00PM-03:00PM'), ('03:00 PM - 06:00 PM', '03:00PM-06:00PM'), ('06:00 PM - 09:00 PM', '06:00PM-09:00PM')], max_length=100, null=True),
        ),
    ]
