# Generated by Django 3.2.9 on 2024-10-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('requestDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
